### PR TITLE
Support splunk metrics

### PR DESCRIPTION
**Pull request by emiller42**

### CODE REVIEW

**Comment by emiller42** [comment]
@lewismc This PR adds support for Splunk Metrics.  Can you review and see if it suits your purposes?

**Comment by emiller42** [comment]
Some screenshots of this in action:

# Counter data
Counter Data

# Gauge data
Gauge data

# Set data
Set data

# Timer data
Timer data

# Example filtering on `metric_type`
Searching by metric_type

**Comment by lewismc** [comment]
Testing today @emiller42

**Comment by lewismc** [comment]
An example of some metrics we are trying to send
```
3 Jun 18:51:05 - DEBUG: airflow.scheduler_heartbeat:1|c
3 Jun 18:51:05 - DEBUG: airflow.scheduler.critical_section_duration:6.958220|ms
3 Jun 18:51:06 - DEBUG: airflow.scheduler.critical_section_duration:6.989922|ms
3 Jun 18:51:08 - DEBUG: airflow.scheduler.critical_section_duration:7.694453|ms
3 Jun 18:51:09 - DEBUG: airflow.scheduler.critical_section_duration:7.632654|ms
3 Jun 18:51:10 - DEBUG: airflow.scheduler.critical_section_duration:7.189173|ms
3 Jun 18:51:10 - DEBUG: airflow.scheduler.critical_section_duration:6.864361|ms
```

**Comment by emiller42** [comment]
@lewismc How is testing going?

**Comment by lewismc** [comment]
Hi @emiller42 testing is ongoing. We have been unsuccessful so far but we think it has something to do with SSL configuration. Still investigating and I will provide an update here once we get further. Thanks for checking in...

**Comment by lewismc** [comment]
@emiller42 I confirm that this PR allows us to send **events** into Splunk Enterprise v8.0.6 with the following configuration
```
{
  debug: true,
  dumpMessages: true,
  flushInterval: 10000,
  backends: ['splunk-statsd-backend'],
  splunk: {
    splunkHost: '...',
    splunkPort: 8088,
    useSSL: true,
    strictSSL: false,
    splunkToken: '...',
    index: '...',
    source: 'statsd',
    sourcetype: '_json',
    useMetrics: false
  },
  servers: [
    {
      server: './servers/tcp'
    },
    {
      server: './servers/udp'
    }
  ]
}
```
This is exactly what we were looking for. Thank you for working so proactively on this PR.

**Comment by lewismc** [comment]
Some more info, the above config results in `metricName` instead of `metric_name`.
We are experimenting setting `useMetrics: true`

**Comment by emiller42** [comment]
That sounds right.  Behavior should be unchanged when `useMetrics: false`.  The difference between `metricName` and `metric_name` only matters when you're sending to a Metrics index. (and thus should have `useMetrics: true`)

**Comment by lewismc** [comment]
Everything appears to be in good order @emiller42

**Pull request merged**
